exclude: |
    (?x)^(
        3rdparty/.+
    )$
repos:
# Others
-   repo: local
    hooks:
    -   id: open3d_code_style
        name: open3d code style check
        description: Open3D default code style checker
        entry: util/check_style.sh
        language: system